---
- name: install node_exporter into Instance
  become: yes
  copy:
    src: node_exporter
    dest: /usr/local/bin
    mode: 0755

- name: Ensures /opt/prometheus/node_exporter dir exists
  file: 
    path: /opt/prometheus/node_exporter
    state: directory
- name: create startup file for node_exporter
  copy:
    src: start.sh
    dest: /opt/prometheus/node_exporter
    mode: 0755

- name: add node_exporter as SystemD service
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system
    mode: 0644

- name: enable & make sure node_exporter service is started
  systemd:
    name: node_exporter
    state: started
    enabled: True
