groups:
- name: node_alerts
  rules:
  - alert: LowDiskSpace
    expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 20
    for: 60m
    labels:
      severity: warning
    annotations:
      summary: Low Disk Space for 1 hour
      console: You may want to check the Node Dashboard at http://grafana.example.com/dashboard/db/node-dashboard
  - alert: DiskWillFillIn4Hours
    expr: predict_linear(node_filesystem_free_bytes{mountpoint="/"}[1h], 4*3600) < 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summanry: Disk on {{ $labels.tenant }}-{{ $lables.type }} will fill in approximately 4 hours.
