---
# PlayBook for Athena Monitoring

# pre_tasks: 
  # EPEL/GPG setup, firewall configuration ...
# - hosts: type_backend | type_cache_queue | ip-10-11-35-5.us-east-2.compute.internal
- hosts: type_backend
  remote_user: ubuntu
  become: yes
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: ~/.ssh/edulogvn-devops-ohio.pem
    # ansible_ssh_private_key_file: ~/.ssh/athena-devops.pem
  roles:
  - systemd_exporter

# tasks:
  # Athena monitoring deployment tasks